[package]
name = "centau/ecr"
description = "ECR is a pure, lightweight Luau library designed for the ECS architecture."
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "LICENSE.md", "default.project.json"]
exclude = ["CHANGELOG.md", ".gitignore", ".gitattributes", "test", "docs", "README.md", ".luarc"]

[dependencies]
