# build settings
remote_theme: mmistakes/minimal-mistakes@4.22.0
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: dark

include: [api, docs]

# customization settings
name: centau
description: A fast entity component system (ECS) for Luau and Roblox.
baseurl: /ecr
url: http://centau.github.io
repository: centau/ecr
logo: /assets/images/logo.svg
breadcrumbs: true
search: true
lunr:
  search_within_pages: true

defaults:
  # api
  - scope:
      path: /api/*
      type: pages
    values:
      layout: single
      sidebar:
        nav: api
  # docs
  - scope:
      path: /docs/*
      type: pages
    values:
      layout: single
      sidebar:
        nav: docs
